### ISSUE TITLE
Can this version work with sm t225 ?

### ISSUE THREAD

**Issue by WindowScary321** [DevZillion/android_kernel_samsung_gta7litewifixx#2]
version: T225OLM6CWL1

**Comment by DevZillion** [comment]
This version would work perfectly with SM-T225 (Android 13), the only issue would be the touchscreen that doesn't work properly, for T225 use https://github.com/DevZillion/android_kernel_samsung_gta7litexx

**Comment by WindowScary321** [comment]
Tks !
